<?php
/**
 * Created by PhpStorm.
 * User: jinjunbin <13585687317@163.com>
 * Date: 2020/1/16
 * Time: 11:20
 */
namespace app\admin\controller;

use app\BaseController;
use think\exception\HttpResponseException;

class AdminBase extends BaseController
{
    public $adminUser = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 判断是否登录, 切换到中间件Auth中处理
        /*if (empty($this->isLogin())) {
            return $this->redirect(url('login/index'), 302);
        }*/
    }

    /**
     * 判断是否登录
     * @return bool
     */
    public function isLogin()
    {
//        dump(session(config('admin.session_admin')));
        $this->adminUser = session(config('admin.session_admin'));
        if (empty($this->adminUser)) {
            return false;
        }
        return true;
    }

    public function redirect(...$args)
    {
        throw new HttpResponseException(redirect(...$args));
    }
}
