<?php
/**
 * AuthBase需要登录的时候继承
 * Created by PhpStorm.
 * User: jinjunbin <13585687317@163.com>
 * Date: 2020/1/20
 * Time: 15:13
 */
namespace app\wechat\controller;

class AuthBase extends WechatBase
{
    public $userId = 0;
    public $username = '';
    public $accessToken = '';
    public $isLogin = 1;
    public function initialize()
    {
        // 关于登录, 可以仿照 admin 下中间件方式来完善
        parent::initialize(); // TODO: Change the autogenerated stub
        if ($this->isLogin == 1) {
            $this->userId = 20; // 测试场景
            return true;
        }
        $this->accessToken = $this->request->header('access-token');
        if (!$this->accessToken || !$this->isLogin()) {
            return $this->show(config('status.not_login'), '没有登录');
        }
    }

    /**
     * 判断用户是否登录
     * @return bool
     */
    public function isLogin()
    {
        $userInfo = cache(config('redis.token_pre').$this->accessToken);//['id'=>1,'username'=>1111];
        if (!$userInfo) {
            return false;
        }
        if (!empty($userInfo['id']) && !empty($userInfo['username'])) {
            $this->userId = $userInfo['id'];
            $this->username = $userInfo['username'];
            return true;
        }

        return false;
    }
}
